DROP TABLE TBL_MEMBER;
DROP TABLE TBL_PRODUCT;
DROP TABLE TBL_PAYMENT;
DROP TABLE TBL_EVENT;
DROP TABLE TBL_EXCHANGE_LIST;
DROP TABLE TBL_REFUND_LIST;
DROP TABLE TBL_NOTICE;
DROP TABLE TBL_QNA;
DROP TABLE TBL_CATEGORY;

-- 제약조건이 있는 테이블 삭제
-- drop table TBL_MEMBER cascade constraints;

CREATE TABLE TBL_MEMBER (
  MEM_CODE VARCHAR(500) PRIMARY KEY,
  MEM_ADMIN VARCHAR(1) CONSTRAINT AA_STATUS NOT NULL,
  CONSTRAINT ADMIN_STATUS CHECK(MEM_ADMIN IN ('Y','N')),
  MEM_NAME VARCHAR(20) NOT NULL,
  MEM_BIRTH VARCHAR(20) NOT NULL,
  GENDER VARCHAR2(10) CHECK (GENDER IN('M', 'F')),
  MEM_ID VARCHAR(20) NOT NULL,
  MEM_PWD VARCHAR(20) NOT NULL,
  MEM_PHONE VARCHAR(20) NOT NULL,
  MEM_ADRR VARCHAR(100) NOT NULL,
  MEM_EMAIL VARCHAR(100) NOT NULL,
  MEM_ACC_DATE DATE DEFAULT SYSDATE,
  MEM_OUT VARCHAR(1) CONSTRAINT NN_STATUS NOT NULL,
  CONSTRAINT OUT_STATUS CHECK(MEM_OUT IN ('Y','N'))
  );
  
  CREATE TABLE TBL_PRODUCT (
  PRO_CODE VARCHAR(500) PRIMARY KEY,
  PRO_NAME VARCHAR(50) NOT NULL,
  PRO_PRICE INT NOT NULL,
  CATE_CODE VARCHAR(20) NOT NULL,
  PRO_SIZE VARCHAR(5) NOT NULL,
  PRO_STOCK INT,
  PRO_ENT_DATE DATE DEFAULT SYSDATE,
  CONSTRAINT FK_CATE_CODE FOREIGN KEY (CATE_CODE) REFERENCES TBL_CATEGORY(CATE_CODE)
);
  
  
 CREATE TABLE TBL_EVENT (
  EVENT_CODE VARCHAR(100) PRIMARY KEY,
  EVENT_NAME VARCHAR(50) NOT NULL,
  EVENT_DETAIL VARCHAR(500),
  EVENT_ADD_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TBL_NOTICE (
  NTC_CODE VARCHAR(100) PRIMARY KEY,
  NTC_TITLE VARCHAR(50) NOT NULL,
  NTC_DETAIL VARCHAR(500)
);


CREATE TABLE TBL_QNA (
  MEM_CODE VARCHAR(500) NOT NULL,
  QNA_CODE VARCHAR(100) PRIMARY KEY,
  QNA_TITLE VARCHAR(50) NOT NULL,
  QNA_DETAIL VARCHAR(500),
  CONSTRAINT FK_MEM_CODE2 FOREIGN KEY (MEM_CODE) REFERENCES TBL_MEMBER(MEM_CODE)
);

CREATE TABLE TBL_CATEGORY (
  CATE_CODE VARCHAR(50) PRIMARY KEY,
  CATE_NAME VARCHAR(50) NOT NULL
);




CREATE TABLE TBL_PAYMENT (
  MEM_CODE VARCHAR(500) NOT NULL,
  PRO_CODE VARCHAR(500) NOT NULL,
  ORDER_NUM VARCHAR(50) PRIMARY KEY,
  DELIVERY_STS VARCHAR(20) NOT NULL,
  MEM_ADRR VARCHAR(100) NOT NULL,
  ORDER_DATE DATE DEFAULT SYSDATE,
  EXCHANGE_YN CHAR(1) CONSTRAINT BB_STATUS NOT NULL,
  CONSTRAINT EXCHANGE_STATUS CHECK(EXCHANGE_YN IN ('Y','N')),
  REFUND_YN CHAR(1) CONSTRAINT CC_STATUS NOT NULL,
  CONSTRAINT REFUND_STATUS CHECK(REFUND_YN IN ('Y','N')),
  CONSTRAINT FK_MEM_CODE FOREIGN KEY (MEM_CODE) REFERENCES TBL_MEMBER(MEM_CODE),
  CONSTRAINT FK_PRO_CODE FOREIGN KEY (PRO_CODE) REFERENCES TBL_PRODUCT(PRO_CODE)
);

CREATE TABLE TBL_VIEW(
    MEM_CODE VARCHAR(50) NOT NULL,
    PRO_CODE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_MEM_CODE1 FOREIGN KEY (MEM_CODE) REFERENCES TBL_MEMBER(MEM_CODE),
    CONSTRAINT FK_PRO_CODE1 FOREIGN KEY (PRO_CODE) REFERENCES TBL_PRODUCT(PRO_CODE)
    
);








  
  
  




